name: shakemap
channels:
- conda-forge
- defaults
- digitalglobe
- ioos
dependencies:
- affine
- amptools
- basemap
- beautifulsoup4
- cartopy
- configobj
- decorator
- defusedxml
- descartes
- docutils
- fiona
- gdal
- h5py
- impactutils
- ipython
- jupyter
- libcomcat
- lockfile
- mapio
- matplotlib
- numexpr
- numpy
- obspy
- openquake.engine
- pandas
- ps2ff
- psutil
- pyproj
- pyshp
- pytest
- pytest-cov
- python=3.5
- python-daemon
- pyyaml
- pyzmq
- rasterio
- requests
- scikit-image
- scipy
- shapely
- sphinx
- strec
- versioneer
- paramiko
- pip:
  - et-xmlfile
  - ipython-genutils
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - prompt-toolkit
  - sphinx-argparse

