name: strecenv
channels:
- conda-forge
- defaults
- ioos
dependencies:
- affine=2.1.0
- asn1crypto=0.22.0
- attrs=17.4.0
- backports=1.0
- backports.functools_lru_cache=1.4
- blas=1.1
- bleach=2.0.0
- boto3=1.5.18
- botocore=1.8.32
- ca-certificates=2017.11.5
- certifi=2017.11.5
- cffi=1.11.2
- chardet=3.0.4
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- coverage=4.4.2
- cryptography=2.1.4
- curl=7.55.1
- cycler=0.10.0
- dbus=1.10.22
- decorator=4.1.2
- docutils=0.14
- entrypoints=0.2.3
- et_xmlfile=1.0.1
- expat=2.2.5
- fiona=1.7.11
- fontconfig=2.12.6
- freetype=2.8.1
- freexl=1.0.4
- future=0.16.0
- gdal=2.1.4
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.7
- giflib=5.1.4
- glib=2.55.0
- gmp=6.1.2
- gst-plugins-base=1.8.0
- gstreamer=1.8.0
- h5py=2.7.1
- hdf4=4.2.13
- hdf5=1.10.1
- html5lib=1.0.1
- icu=58.2
- idna=2.6
- ipykernel=4.7.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.1.1
- jdcal=1.3
- jedi=0.11.1
- jinja2=2.10
- jmespath=0.9.3
- jpeg=9b
- json-c=0.12.1
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.2
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- kealib=1.4.7
- krb5=1.14.2
- libdap4=3.18.3
- libffi=3.2.1
- libgdal=2.1.4
- libiconv=1.15
- libnetcdf=4.4.1.1
- libpng=1.6.34
- libpq=9.6.3
- libsodium=1.0.15
- libspatialite=4.3.0a
- libssh2=1.8.0
- libtiff=4.0.9
- libxcb=1.12
- libxml2=2.9.7
- libxslt=1.1.32
- lxml=4.1.1
- markupsafe=1.0
- matplotlib=2.1.2
- mistune=0.8.3
- munch=2.2.0
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=5.9
- notebook=5.4.0
- numpy=1.14.0
- obspy=1.1.0
- openblas=0.2.20
- openjpeg=2.1.2
- openpyxl=2.5.0
- openssl=1.0.2n
- pandas=0.22.0
- pandoc=2.1.1
- pandocfilters=1.4.1
- parso=0.1.1
- pcre=8.39
- pexpect=4.3.1
- pickleshare=0.7.4
- pip=9.0.1
- pluggy=0.6.0
- proj4=4.9.3
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- py=1.5.2
- pycparser=2.18
- pygments=2.2.0
- pyopenssl=17.4.0
- pyparsing=2.2.0
- pyproj=1.9.5.1
- pyqt=5.6.0
- pysocks=1.6.8
- pytest=3.4.0
- pytest-cov=2.5.1
- python=3.5.4
- python-dateutil=2.6.1
- pytz=2017.3
- pyzmq=16.0.2
- qt=5.6.2
- qtconsole=4.3.1
- rasterio=0.36.0
- readline=7.0
- requests=2.18.4
- s3transfer=0.1.12
- scipy=1.0.0
- send2trash=1.4.2
- setuptools=38.4.0
- shapely=1.6.4
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- snuggs=1.4.1
- sphinx=1.6.6
- sphinxcontrib-websupport=1.0.1
- sqlalchemy=1.2.1
- sqlite=3.20.1
- terminado=0.8.1
- testpath=0.3.1
- tk=8.6.7
- tornado=4.5.3
- traitlets=4.3.2
- urllib3=1.22
- wcwidth=0.1.7
- webencodings=0.5
- wheel=0.30.0
- widgetsnbextension=3.1.3
- xerces-c=3.2.0
- xlrd=1.1.0
- xlwt=1.3.0
- xorg-libxau=1.0.8
- xorg-libxdmcp=1.1.2
- xz=5.2.3
- zeromq=4.2.1
- zlib=1.2.11
- libgfortran=3.0.0
- util-linux=2.21
- pip:
  - backports.functools-lru-cache==1.4
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - ./impact-utils.zip
  - ./libcomcat.zip
  - ./mapio.zip
  - ./strec.zip


